anthill/projects/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('anthill.projects.views',
    url(r'^tag/(?P<tag>[^/]+)/$', 'tag_archive', name='projects_tagged'),
    url(r'^(?P<slug>[-\w]+)/$', 'project_detail', name='project_detail'),
)

urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.contrib import admin
from django.http import HttpResponsePermanentRedirect
from django.shortcuts import get_object_or_404
from django.views.generic.simple import redirect_to
from blogdor.models import Post
from labs.feeds import LabsLatestPosts, LabsLatestForTag, LabsLatestForAuthor
from labs.forms import LabsContactForm

admin.autodiscover()

blog_feeds = {
    'latest_fburner': LabsLatestPosts,
    'tag': LabsLatestForTag,
    'author': LabsLatestForAuthor,
}


def thegreatredirector(request, year, slug):
    post = get_object_or_404(Post.objects.published(), date_published__year=year, slug=slug)
    date_str = post.date_published.strftime("%Y/%m/%d")
    url = "http://sunlightfoundation.com/blog/%s/%s/" % (date_str, post.slug.rstrip('-'))
    return HttpResponsePermanentRedirect(url)


urlpatterns = patterns('',
    # apps
    url(r'^admin/', include(admin.site.urls)),
    url(r'^search/', include('haystack.urls')),
    url(r'^wiki/', include('markupwiki.urls')),

    # blog/blogdor
    url(r'^blog/feeds/(?P<url>.*)/$', 'django.contrib.syndication.views.feed',
        {'feed_dict': blog_feeds}, name="blogdor_feeds"),

    # redirects
    url(r'^events/', redirect_to, {'url': 'http://meetup.com/sunlightfoundation/'}),
    url(r'^api/', redirect_to, {'url': 'http://services.sunlightlabs.com/api/'}),
    # url(r'^people/', redirect_to, {'url': '/about/'}),
    # url(r'^projects/all/', redirect_to, {'url': '/projects/'}),
    # url(r'^projects/official/', redirect_to, {'url': '/projects/'}),
    # url(r'^projects/community/', redirect_to, {'url': '/projects/'}),

    # labs specific
    url(r'^images/(?P<image_path>.*)$', 'labs.views.image_wrapper',
        name="image_wrapper"),
    url(r'^photobooth/$', redirect_to,
        {'url': 'http://www.flickr.com/photos/sunlightfoundation/sets/72157632180391380/'}),

    url(r'^$', 'labs.views.index', name='index'),
)

# shutdown redirects

urlpatterns += patterns('',
    url(r'^about/', redirect_to, {'url': 'http://sunlightfoundation.com/labs/'}),
    url(r'^blog/(?P<year>\d{4})/(?P<slug>[\w-]+)/$', thegreatredirector),
    url(r'^blog/', redirect_to, {'url': 'http://sunlightfoundation.com/blog/'}),
    url(r'^contact/', redirect_to, {'url': 'http://sunlightfoundation.com/contact/'}),
    url(r'^join/', redirect_to, {'url': 'http://sunlightfoundation.com/join/'}),
    url(r'^people/', redirect_to, {'url': 'http://sunlightfoundation.com/people/'}),
    url(r'^projects/', redirect_to, {'url': 'http://sunlightfoundation.com/projects/'}),

    # keep these for reverse url
    url(r'^blog/', include('blogdor.urls')),
    url(r'^contact/$', 'labs.views.contact_form', name='contact_form'),
    url(r'^people/(?P<username>\w+)/$', 'labs.views.profile_redirect',
        name='user_profile'),
    url(r'^projects/', include('anthill.projects.urls')),
)


if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

anthill/projects/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.contrib.contenttypes import generic
from django.conf import settings
from tagging.fields import TagField
from markupfield.fields import MarkupField

class Project(models.Model):
    slug = models.SlugField('unique identifier for project',
                            max_length=50, unique=True,
                            help_text="(this will become part of your projects URL)")
    name = models.CharField('displayed name of project', max_length=100)
    description = MarkupField(default_markup_type='markdown', escape_html=True)
    official = models.BooleanField(default=False)
    creation_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    tags = TagField('Tags')

    lead = models.ForeignKey(User, related_name='projects_lead_on')
    members = models.ManyToManyField(User, through='Role')

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('project_detail', args=[self.slug])

    def get_members(self):
        return self.members.filter(project_roles__status='A')

ROLE_STATUSES = (
    ('P', 'Pending'),
    ('A', 'Active'),
    ('R', 'Retired')
)

class RoleManager(models.Manager):

    def active(self):
        return self.filter(status='A')

class Role(models.Model):
    user = models.ForeignKey(User, related_name='project_roles')
    project = models.ForeignKey(Project, related_name='roles')
    join_time = models.DateField(auto_now_add=True)
    status = models.CharField(choices=ROLE_STATUSES, max_length=1, default='P')
    message = models.TextField(blank=True)

    objects = RoleManager()

DEFAULT_LINK_TYPES = (
    (0, 'website'),
    (1, 'source'),
    (2, 'documentation'),
    (3, 'download'),
    (4, 'email'),
)
LINK_TYPES = getattr(settings, 'ANTHILL_LINK_TYPES', DEFAULT_LINK_TYPES)

class Link(models.Model):
    name = models.CharField(max_length=100)
    url = models.URLField()
    link_type = models.PositiveSmallIntegerField(choices=LINK_TYPES, default=0)
    project = models.ForeignKey(Project, related_name='links')

    class Meta:
        ordering = ['link_type']

anthill/projects/views.py
from django.views.generic.list_detail import object_detail
from tagging.views import tagged_object_list
from anthill.projects.models import Project

def tag_archive(request, tag):
    """
        Paginated listing of ``Project``s by tag.

        Template: projects/projects_list.html

        Context:
            tag          - tag being displayed
            project_list - list of projects

            See ``django.views.generic.list_detail.object_list`` for pagination variables.
    """
    qs = Project.objects.select_related()
    if hasattr(qs, '_gatekeeper'):
        qs = qs.approved()
    return tagged_object_list(request, qs, tag, paginate_by=10,
                              template_object_name='project',
                              extra_context={'tag':tag},
                              allow_empty=True)

def project_detail(request, slug):
    """
        Detail view of a ``Project``.

        Template: projects/project_detail.html

        Context:
            project - ``Project`` instance
    """
    # explicitly don't use _gatekeeper check here
    return object_detail(request,
                         queryset=Project.objects.select_related().all(),
                         slug=slug, template_object_name='project')

templates/projects/base.html
{% extends "base.html" %}
{% load media %}

{% block title %}
{{block.super}}: Ideas
{% endblock %}

{% block extrahead %}
    {% js "voting.js" %}
{% endblock %}

{% block bodyclass %}projects{% endblock %}

{% block sidebar %}

<h3 class="space">How Our Process Works</h3>
<div id="process" class="module">	
    <ol id="processList">
        <li>
            <span id="mess">Mess</span>
            <p>Disorganized government data needs your help.</p>
        </li>
        <li>
            <span id="ideas">Ideas</span>
            <p>Ideas are born on how to make government data more useful and accessible.</p>
        </li>
        <li>
            <span id="community">Community</span>
            <p>The community contributes to these ideas to make them reality.</p>
        </li>	
        <li>
            <span id="transparency">Transparency</span>
            <p>We're one step closer to government transparency.</p>
        </li>
        <a class="learnBtn" href="#">Learn More</a>
    </ol>	
</div>	
<div class="clear"></div>
{% endblock %}

templates/projects/project_detail.html
{% extends "projects/base.html" %}
{% load people %}
{% load blog %}
{% load tagging_tags %}

{% block title %}
Sunlight Labs: Projects - {{project.name}}
{% endblock title %}

{% block content %}
{% if project.moderation_object.moderation_status == -1 %}

<div id="ideas" class="module">
    <div class="contentHeader">
        <h2 class="ideas">Project Removed</h2>
    </div>
    <div class="module">
        <p>
        This project has been removed.

        <dl class="moderationMetadata">
            <dt>Removed by</dt>
            <dd>{% display_name project.moderation_object.moderation_status_by %}</a></dd>
            <dt>Date</dt>
            <dd>{{project.moderation_object.moderation_status_date|date}}</dd>
            <dt>Reason</dt>
            <dd>{{project.moderation_object.moderation_reason}}</dd>
        </dl>
        </p>
    </div>
</div>

{% else %}
<div id="projects" class="module">

    <div class="contentHeader">
        <h2 class="projects">{{project.name}}</h2>
    </div>

    {% tags_for_object project as tags %}

    <div id="projectDetail" class="module">
        <dl class="entryMetadata">
            <dt>Became a project on</dt>
            <dd>{{project.creation_date|date}}</dd>
        </dl>

        <div id="languages">
            {% if "d4a-winner" in project.tags %}
            <img alt="Design For America Winner" title="Design For America Winner" src="http://assets.sunlightlabs.com/site3/images/icon_apps1.png">
            {% else %}
                {% if "d4a" in project.tags %}
                <img alt="Design For America Entry" title="Design For America Entry" src="http://assets.sunlightlabs.com/site3/images/icon_apps.png">
                {% endif %}
            {% endif %}

            <h3 id="skillsHeader">Tags</h3>
            <ul>
                {% for tag in tags %}
                <li><a href="{% url projects_tagged tag %}">{{tag}}</a></li>
                {% endfor %}
            </ul>
        </div>

        <div id="project_mainDetails">
            <div id="projectDescription">{{project.description}}</div>
            <ul>
                {% for link in project.links.all %}
                <li class="{{link.get_link_type_display}}_link">
                    <a title="{{link.get_link_type_display}}" href="{{link.url}}">{{link.name}}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

{% block sidebar %}
{% if project.moderation_object.moderation_status != -1 %}
<h3 class="space">Project Participants</h3>
<div class="module">
    <h4>Lead</h4>
    <a id="leadParticipant" href="{{project.lead.get_absolute_url}}">
        {% gravatar project.lead.email %}
        <span id="leadName">{% display_name project.lead %}</span>
    </a>
    <div class="clear"></div>

    {% with project.get_members as members %}
    {% if members %}
    <h4 id="teamHeader">Team</h4>
    <ul id="teamParticipants">
        {% for member in members %}
            <li>
                <a href="{{member.get_absolute_url}}">{% gravatar member.email %}
                    <span>{% display_name member %}</span>
                </a>
            </li>
        {% endfor %}
        <div class="clear"></div>
    </ul>
    {% endif %}
    {% endwith %}
</div>

<div class="clear"></div>
{% endif %}
{% endblock %}

templates/projects/project_list.html
{% extends "projects/base.html" %}

{% block title %}
Sunlight Labs:
Projects
{% endblock title %}

{% block content %}
<div class="contentHeader">
    <h2 class="projects projectHeader">
        {% if projects == "official" %} Official {% endif %}
        {% if projects == "community" %} Community {% endif %}
        Projects
        {% if tag %} tagged {{tag}} {% endif %}
    </h2>
    <a class="tip rss" href="/projects/feeds/latest/">Subscribe to this feed</a>
    <div class="clear"></div>
</div>
<div id="projects" class="module">
    {% for project in project_list %}
        {% include "projects/project_summary.html" %}
    {% endfor %}
</div>
{% include "pagination_div.html" %}
{% endblock %}

templates/projects/project_summary.html
{% load people %}

<div class="project">
    <div class="projectContent">
        <h3><a href="{{project.get_absolute_url}}">{{project}}</a></h3>
        <dl class="entryMetadata">
            <dt>Lead by</dt>
            <dd><a class="seperationBlock" href="{{project.lead.get_absolute_url}}">{% display_name project.lead %}</a></dd>
            <dt>Added</dt>
            <dd>{{project.creation_date|date}}</dd>
        </dl>
        <div class="short_desc">{{project.description|truncatewords_html:50}}</div>
        <p><a class="viewAll more" href="{{project.get_absolute_url}}">More Details</a></p>
    </div>
</div>

templates/projects/projects_and_ideas.html
{% extends "projects/base.html" %}

{% block title %}
Sunlight Labs: Projects
{% endblock title %}

{% block content %}
<div class="contentHeader">
    <h2 class="projects projectHeader">Projects</h2>
    <a class="tip rss" href="/projects/feeds/latest/">Subscribe to this feed</a>
    <a id="projectCreate" href="/projects/new/">Create A New Project</a>
    <div class="clear"></div>
</div>
<div id="projects" class="module">
    <p class="tip">These are active projects that are currently being worked on in the labs community. <strong><br/> <a href="{% url all_project_asks %}">Feel free to help</a></strong> on a project you're interested in or just <strong>keep your eye out for the final product</strong>.</p>
    <div id="projectNav">
        <ul>
            <li id="allProjects">
                <a class="active" href="{% url all_projects %}">All Projects</a>
            </li>  
            <li id="labsProjects">
                <a href="{% url official_projects %}">Labs Projects</a>
            </li>  
            <li id="communityProjects">
                <a href="{% url community_projects %}">Community Projects</a>
            </li>
        </ul>
    </div>
    {% for project in projects %}
        {% include "projects/project_summary.html" %}
    {% endfor %}
    <p class="arrow"><a class ="viewAll" href="{% url all_projects %}">View All</a></p>
</div>

{% endblock content %}

templates/projects/projects_list.html
{% extends "ideas/base.html" %}

{% block content %}
<div class="contentHeader">
    <h2 class="projects">Projects</h2>
</div>
<div id="projects" class="module">
    <p class="tip">These are active projects that are currently being worked on in the labs community. <strong><br/> Feel free to help</strong> on a project you're interested in or just <strong>keep your eye out for the final product</strong>.</p>
    {% for project in project_list %}
        {% include "projects/project_summary.html" %}
    {% endfor %}
</div>
{% endblock %}